### PR TITLE
Updated Windows file associations

### PR DESCRIPTION
**Pull request by vldgeorgiev**
Added file association for the .thconfig extension
Updated the .th and .th2 associations to have different descriptions

### CODE REVIEW

**Review by mbudaj — COMMENTED** [review]
Are you sure the quotes which you omitted are not necessary?

**Comment by vldgeorgiev** [comment]
They are, I must have stripped them while editing the file. I'll put them back.

While we are at it, the installer tries to set associations for both the current user and in Classes_Root. Is there any special reason for it?
Since the installer places files in Program Files for all users anyway, it would be better to set the associations for all users too.

Or to have an option to install for all or current user, but that might be in a future PR.

**Comment by mbudaj** [comment]
No idea why HKCU was added in 2008. Maybe it's some remnant from testing the installation for unprivileged users?

Installation option for all or current current user is a good idea. Some users require also portable distribution. This would require a modification of therion and xtherion to use the path to the executable for locating TeX, mpost etc. if there is no registry value set.

**Comment by vldgeorgiev** [comment]
Sorry for the delay. I will add an option to select All users/This user.
Lately I have other personal stuff to do and very limited time, so it will happen in a week or two.

**Comment by vldgeorgiev** [comment]
I added an option in the installer to select "Current user" or "All users"
To be honest the script now seems over-complicated just for this simple option. But if you think that people need to use the installer without admin rights, this will do it. It will install the app under Users\AppData\Local for limited users.

**Review by mbudaj — COMMENTED** [review]
- The code still uses HKLM keys. Would it work without admin rights? (no time to test it now)

- InnoSetup docs recommend using PrivilegesRequired=lowest. Is there a reason to use "none"?

**Comment by vldgeorgiev** [comment]
There are two copies of the registry keys, one with HKLM and the other with
HKCU. Which one is used depends on the Check condition, so for a limited
user only the HKCU will be applied.

The problem with privileges "lowest" is that the installer doesn't have
access to the common folders like the global start menu. With "admin" it
does, but the installer can not be ran without admin rights, which defeats
the purpose of having a limited user run it. The "none" is not documented,
but works for both types of users.

I tested the installer with both admin and regular user.

**Pull request merged**
